Use golangci-lint run for linting (#95)
GolangCI Lint scans code with different linters and reports issues
directly withing github PR also it's easy to configure.

Documentation: https://golangci-lint.run/

Signed-off-by: Sanket Sudake <sanketsudake@gmail.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -21,16 +21,40 @@ jobs:
       uses: actions/setup-go@v2
       with:
         go-version: 1.16
-    - name: Install golint
+
+    - uses: actions/cache@v2
+      with:
+        path: ~/go/pkg/mod
+        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+        restore-keys: |
+          ${{ runner.os }}-go-
+
+    - name: Verify dependencies
       run: |
-        go get -u golang.org/x/lint/golint
-    - name: Before build
-      run: |
-        echo Workflow trigger - ${{ github.event_name }}
-        ./hack/verify-gofmt.sh
-        ./hack/verify-govet.sh
-        ./hack/verify-golint.sh
         go mod verify
+        go mod download
+        LINT_VERSION=1.41.1
+        curl -fsSL https://github.com/golangci/golangci-lint/releases/download/v${LINT_VERSION}/golangci-lint-${LINT_VERSION}-linux-amd64.tar.gz | \
+          tar xz --strip-components 1 --wildcards \*/golangci-lint
+        mkdir -p bin && mv golangci-lint bin/
+
+    - name: Run checks
+      run: |
+        STATUS=0
+        assert-nothing-changed() {
+          local diff
+          "$@" >/dev/null || return 1
+          if ! diff="$(git diff -U1 --color --exit-code)"; then
+            printf '\e[31mError: running `\e[1m%s\e[22m` results in modifications that you must check into version control:\e[0m\n%s\n\n' "$*" "$diff" >&2
+            git checkout -- .
+            STATUS=1
+          fi
+        }
+        assert-nothing-changed go fmt ./...
+        assert-nothing-changed go mod tidy
+        bin/golangci-lint run --out-format=github-actions --timeout=5m || STATUS=$?
+        exit $STATUS
+
     - name: Build
       run: go build -v ./...
 
